Problem Statement 1:

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically,
when increasing is False, the i-th output column is the input vector raised element-wise
to the power of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [35]:
import numpy as np

def vand(arr):
    l=len(arr)
    ar=[]
    for n in arr:
        i=0
        while i<l:
            ar.append(n**i)
            i+=1
    vand_arr=np.array(ar)
    print(vand_arr.reshape(l,l))
m = [4,7,5,9,10]    
vand(m)
        
    

[[    1     4    16    64   256]
 [    1     7    49   343  2401]
 [    1     5    25   125   625]
 [    1     9    81   729  6561]
 [    1    10   100  1000 10000]]
